---
# FIX: Fehlender YAML-Dokument-Header (---) ergänzt

- name: Syncthing Autostart für COSMIC Desktop einrichten
  hosts: all
  become: false  # Muss im User-Kontext ausgeführt werden

  tasks:
    - name: Autostart-Verzeichnis sicherstellen
      ansible.builtin.file:
        path: "~/.config/autostart"
        state: directory
        mode: '0755'

    - name: Syncthing Autostart-Datei erstellen
      ansible.builtin.copy:
        dest: "~/.config/autostart/syncthing.desktop"
        content: |
          [Desktop Entry]
          Type=Application
          Name=Syncthing
          Comment=Dateisynchronisation im Hintergrund
          Exec=/usr/bin/syncthing serve --no-browser
          Icon=syncthing
          Terminal=false
          Categories=Network;FileTransfer;
          X-GNOME-Autostart-enabled=true
        mode: '0644'
