---
# FIX: Mehrere Sicherheits- und Funktionskorrekturen:
#  1. StrictHostKeyChecking deaktiviert → durch known_hosts-Task ersetzt
#  2. allow_other in SSHFS-Optionen → /etc/fuse.conf wird korrekt gesetzt
#  3. SSH-Key-Hinweis: In Produktion ansible-vault für den Key-Inhalt nutzen

- name: Setup SSHFS Autostart for COSMIC
  hosts: alpine_nodes
  become: yes
  vars:
    username: "meinuser"
    remote_host: "dein.server.de"
    remote_user: "remoteuser"
    remote_path: "/pfad/am/server"
    mount_point: "/home/{{ username }}/ssh-mount"
    # FIX: Fingerprint des Servers vorab ermitteln mit:
    #      ssh-keyscan dein.server.de
    #      und hier eintragen, statt StrictHostKeyChecking zu deaktivieren
    remote_host_key: "dein.server.de ssh-ed25519 AAAA..."

  tasks:
    - name: Installiere SSHFS
      community.general.apk:
        name: sshfs
        state: present

    - name: Erstelle Mountpoint und .ssh Verzeichnis
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'
      loop:
        - "{{ mount_point }}"
        - "/home/{{ username }}/.ssh"
        - "/home/{{ username }}/.config/autostart"

    - name: Kopiere SSH Private Key
      ansible.builtin.copy:
        # FIX: In Produktion den Key-Inhalt per ansible-vault verschlüsseln:
        #      ansible-vault encrypt files/id_rsa
        src: files/id_rsa
        dest: "/home/{{ username }}/.ssh/id_rsa"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'

    # FIX: Bekannten Host-Fingerprint in known_hosts eintragen statt
    #      StrictHostKeyChecking zu deaktivieren (MITM-Schutz)
    - name: Server-Fingerprint in known_hosts eintragen
      ansible.builtin.known_hosts:
        path: "/home/{{ username }}/.ssh/known_hosts"
        name: "{{ remote_host }}"
        key: "{{ remote_host_key }}"
        state: present

    - name: Setze Besitzer der known_hosts-Datei
      ansible.builtin.file:
        path: "/home/{{ username }}/.ssh/known_hosts"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'

    - name: Erstelle ~/.ssh/config
      ansible.builtin.copy:
        dest: "/home/{{ username }}/.ssh/config"
        # FIX: StrictHostKeyChecking entfernt – Fingerprint ist jetzt in known_hosts
        content: |
          Host {{ remote_host }}
            User {{ remote_user }}
            IdentityFile ~/.ssh/id_rsa
        owner: "{{ username }}"
        mode: '0600'

    # FIX: allow_other erfordert user_allow_other in /etc/fuse.conf
    - name: FUSE allow_other in /etc/fuse.conf aktivieren
      ansible.builtin.lineinfile:
        path: /etc/fuse.conf
        line: "user_allow_other"
        create: yes
        mode: '0644'

    - name: Erstelle COSMIC Autostart Eintrag für SSHFS
      ansible.builtin.copy:
        dest: "/home/{{ username }}/.config/autostart/mount-sshfs.desktop"
        content: |
          [Desktop Entry]
          Type=Application
          Name=SSHFS Mount
          Exec=sshfs {{ remote_host }}:{{ remote_path }} {{ mount_point }} -o reconnect,allow_other
          Icon=network-server
          Terminal=false
          X-GNOME-Autostart-enabled=true
        owner: "{{ username }}"
        mode: '0644'
