---
# FIX: Passwörter nie im Klartext. Dieses Playbook erwartet eine Vault-Datei.
# Vault-Datei anlegen mit: ansible-vault create group_vars/all/vault.yaml
# Inhalt der Vault-Datei:
#   vault_user_password: "dein_sicheres_passwort"
#
# Ausführen mit: ansible-playbook alpine_user.yaml --ask-vault-pass

- name: Setup User with Auto-Mount Encrypted Home
  hosts: alpine_nodes
  become: yes
  vars:
    username: "meinuser"
    # FIX: Passwort kommt aus Ansible Vault, nicht mehr im Klartext
    user_password: "{{ vault_user_password }}"

  tasks:
    - name: Benötigte Pakete installieren
      community.general.apk:
        name:
          - ecryptfs-utils
          - pam-ecryptfs
          - rsync
          # FIX: fish installieren, da es als Shell gesetzt wird
          - fish
        state: present

    - name: Kernel-Modul laden
      community.general.modprobe:
        name: ecryptfs
        state: present

    # FIX: Shell auf /usr/bin/fish geändert (konsistent mit alpine_pkg_install.yaml;
    #      /bin/zsh wird nirgends installiert)
    - name: Nutzer erstellen
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ user_password | password_hash('sha512') }}"
        shell: /usr/bin/fish
        create_home: yes

    - name: eCryptfs Verzeichnisstruktur initialisieren
      ansible.builtin.shell: |
        echo "{{ user_password }}" | ecryptfs-setup-private -u {{ username }} --nopwcheck --login
      args:
        creates: "/home/{{ username }}/.ecryptfs"
      # Passwort kommt zur Laufzeit aus Vault – kein Klartext im Playbook

    - name: PAM Konfiguration - Auth (Passwort-Übergabe)
      ansible.builtin.lineinfile:
        path: /etc/pam.d/base-auth
        line: "auth    required    pam_ecryptfs.so unwrap"
        insert_before: "auth    required    pam_unix.so"

    - name: PAM Konfiguration - Session (Automatischer Mount)
      ansible.builtin.lineinfile:
        path: /etc/pam.d/base-session
        line: "session required    pam_ecryptfs.so layout=map"
        state: present

    - name: PAM Konfiguration - Password (Synchronisation)
      ansible.builtin.lineinfile:
        path: /etc/pam.d/base-password
        line: "password required    pam_ecryptfs.so"
        state: present
