---
- name: Alpine COSMIC Desktop Setup
  hosts: alpine_nodes
  become: yes

  tasks:
    - name: Repositories auf Edge umstellen (erforderlich für COSMIC)
      ansible.builtin.copy:
        dest: /etc/apk/repositories
        content: |
          https://dl-cdn.alpinelinux.org
          https://dl-cdn.alpinelinux.org
          https://dl-cdn.alpinelinux.org

    - name: System-Update und Installation der Pakete
      community.general.apk:
        update_cache: yes
        upgrade: yes
        name:
          - cosmic-session
          - cosmic-greeter
          - flatpak
          - rustybox
          - dropbear
          - dropbear-ssh
          - mesa-dri-gallium # GPU Treiber
          - udev
        state: present
    
    - name: Syncthing Paket installieren
      community.general.apk:
        name: syncthing
        state: present
        update_cache: yes

    - name: Dienste aktivieren (udev & dropbear)
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop: [udev, dropbear]

    - name: Rustybox als Standard-Shell für Nutzer setzen
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/rustybox

    - name: Grafischen Login (Greetd) konfigurieren
      ansible.builtin.service:
        name: greetd
        enabled: yes
        state: started

    - name: Flatpak Alpine Repo hinzufügen
      ansible.builtin.command: 
        cmd: flatpak remote-add --if-not-exists flathub https://flathub.org
    
    - name: NetworkManager Pakete installieren
      community.general.apk:
        name: 
          - networkmanager
          - networkmanager-cli
          - networkmanager-wifi  # Wichtig für WLAN-Support
          - py3-gobject3         # Erforderlich für das nmcli-Modul
          - dbus
        state: present
        update_cache: yes

    - name: D-Bus und NetworkManager Dienste aktivieren
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - dbus
        - networkmanager
    
    - name: Stelle sicher, dass das Community-Repository aktiviert ist
      command: setup-apkrepos -c
      register: repo_result
      changed_when: "'added' in repo_result.stdout"

    - name: Installiere Audio-Pakete
      community.general.apk:
        name:
          - pipewire
          - wireplumber
          - pipewire-pulse
          - pipewire-alsa
          - alsa-utils
        state: present
        update_cache: yes

    - name: Fuege User zur Gruppe 'audio' und 'video' hinzu
      user:
        name: "{{ ansible_user }}"
        groups: audio,video
        append: yes

    - name: Erstelle Konfigurationsverzeichnisse (optional für Anpassungen)
      shell: |
        cp -a /usr/share/pipewire /etc/
        cp -a /usr/share/wireplumber /etc/
      args:
        creates: /etc/pipewire/pipewire.conf

    - name: Aktiviere PipeWire und WirePlumber als User-Services
      # Benötigt Alpine 3.22+ für native User-Services
      shell: |
        rc-update -U add pipewire gui
        rc-update -U add wireplumber gui
        rc-update -U add pipewire-pulse gui
      become: no
    
    - name: Update Paket-Index und installiere Fish & Alacritty
      community.general.apk:
        name:
          - fish
          - alacritty
        state: present
        update_cache: yes

    - name: Setze Fish als Standard-Shell für den Benutzer
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/fish

    - name: Installiere Fish-Completions für Alacritty (optional)
      community.general.apk:
        name: alacritty-fish-completion
        state: present
    
